name: drift_manager
description: A high-level query builder built with drift.
version: 1.0.0-wip
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  drift3:
  drift_sqlite:
  meta: ^1.17.0
